a= input('digite algo que iremos catalogar: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É um numero ?', a.isnumeric() )
print('É algabetico ?', a.isalpha())
print('É alphanumerio ?', a.isalnum())
print('É Maiuscula ?', a.isupper())
print('É Minuscula ?', a.islower())
print('é capitalizada ?', a.istitle())